name: Deploy HTML Files to AppServiceCMST385
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'CMST385-cbartolomeusobrinho'
        slot-name: 'production'
        publish-profile: ${{ secrets.AppServiceCMST385 }}
